### PR TITLE
fail_onerror to support rabbitmq fail to start on error when node reg…

### LINKED ISSUE #41: rabbitmq-server doesn't fail to start if node is not able join cluster
Hi, 
We just successfully completed a proof of concept on using rabbitmq-autocluster plugin and consul for RabbitMQ AWS deployment. 

However, We just have a concern on following behaviour,  
    
 rabbitmq-server starts as a standalone one node cluster (instead of fail/terminate) if it is not able to join existing cluster nodes due to some connectivity issues between existing nodes and new node, but per consul existing nodes are healthy. auto cluster plugin is logging below error message.

Is it possible to change the behavior to fail/terminate RabbitMQ node at start-up if it is not able to join cluster?

Our RabbitQ AWS deployment requires minimum of 3 nodes and maximum 6 nodes in a RabbitMq cluster and configure ELB for the cluster nodes (EC2 Instnaces). We don't want to add any EC2 instance ( Rabbit Node) to ELB  which is not part of the cluster.

INFO REPORT==== 21-Jan-2016::16:27:31 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Thu, 21 Jan 2016 21:27:31 GMT"},
                              {"content-length","0"},
                              {"content-type","text/plain; charset=utf-8"}],
                             []}}]

=INFO REPORT==== 21-Jan-2016::16:27:31 ===
autocluster: Registered node

=INFO REPORT==== 21-Jan-2016::16:27:31 ===
autocluster: Node is only node in the cluster

=ERROR REPORT==== 21-Jan-2016::16:27:31 ===
autocluster: Can not communicate with cluster nodes: ['rabbit@ip-205-200-226']

Thanks 
Giri

### PR DESCRIPTION
**Pull request by Giri-Chintala**
…istering with consul/etcd/dns or joining existing cluster.

fixes #41 . However still need to add support for N retries before declaring error.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Perhaps it should be `FAIL_ON_ERROR`. Having underscores in some places but not all is very confusing.

File: src/autocluster.erl [hunk 1]
```diff
@@ -28,7 +28,10 @@ init() ->
     {ok, DiscoveryNodes} -> ensure_clustered(DiscoveryNodes);
     error ->
       autocluster_log:info("Error in ensuring clustered"),
-      ok
+      case autocluster_config:get(fail_onerror) of
```
Comment (michaelklishin) [inline src/autocluster.erl]: Please at least make it `fail_on_error`. I'd suggest a `cluster_formation_failure_mode` with two values (`stop` and `ignore`) because `fail_on_error` is not particularly descriptive as to what will fail and what the error is.

Comment (Giri-Chintala) [inline src/autocluster.erl]: agreed! `cluster_formation_failure_mode` is more descriptive.

**Comment by Giri-Chintala** [comment]
@gmr . Could please merge this PR to master and 3.5.x..  ?
